### ISSUE TITLE
import contact warning

### ISSUE THREAD

**Issue by LSchwiedrzik** [rmcgibbo/nebterpolator#4]
I've recently started working with TeraChem's ab-initio nanoreactor, and I want to use nebterpolator to analyze the resulting trajectories. Nebterpolator works on my system, but it is quite slow and prints a warning at the beginning of every run:

> UserWarning: 'contact' cannot be imported (topology tools will be slow.)

I hunted around a bit in the code, and I found a line in molecule.py that just says

> import contact

I have not been able to identify what exactly 'contact' is. I can't seem to be able to find it via google, so I figured it might not be a python library but rather a script that was not uploaded with the rest of the nebterpolator code. Could you shed some light on what 'contact' is, howI might be able to access it, and whether it will indeed speed up calculations?
Thanks in advance!

**Comment by leeping** [comment]
I'm sorry for the inconvenience - I think the code may have been left out of the repository.  There are two ways to fix this problem:

1) The files are included in older ForceBalance commits, such as this one: https://github.com/leeping/forcebalance/tree/95e2458a87689d40a17f85a7052a14ebcd238263

Not only do you need src/contact.py, you also need ext/contact and some lines in setup.py to compile the C extensions.

2) You may use an updated version of molecule.py, such as this one:
https://github.com/leeping/forcebalance/blob/master/src/molecule.py

This doesn't require contact.py anymore, and it's almost as fast.

Whichever solution you choose, I'd appreciate if you could submit a PR to this repository containing the fix.

Thanks,

- Lee-Ping

**Comment by LSchwiedrzik** [comment]
I ended up using the updated version of molecule.py, just submitted a PR from my fork of the repository. Thanks for your help!
